#!/bin/bash
echo "🎯 FanCake Staging - Ultra Simple Deploy"
echo "========================================"
echo ""
echo "Scegli metodo:"
echo ""
echo "1) Netlify (DRAG & DROP)"
echo "   Apri: https://app.netlify.com"
echo "   Trascina la cartella 'frontend'"
echo ""
echo "2) Vercel (1 comando)"
echo "   npm install -g vercel"
echo "   cd frontend && vercel --prod"
echo ""
echo "3) GitHub Pages (gratis)"
echo "   git push"
echo "   Settings > Pages > main branch /frontend"
echo ""
echo "4) Localhost (test)"
echo "   cd frontend"
echo "   python3 -m http.server 8000"
echo ""
echo "🔗 Database già attivo:"
echo "   https://lftlvycvgauzrryyqxpu.supabase.co"
echo ""
echo "✅ Tutto configurato automaticamente!"
